name: Example Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print GitHub Variables
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Commit SHA: $GITHUB_SHA"
          echo "Branch/Tag: $GITHUB_REF"
          echo "Workflow: $GITHUB_WORKFLOW"
