name: Test Secrets in Conditionals

on: [push]

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    env:
      job_secret: ${{ secrets.JobSecret }}  # Set the secret as a job-level environment variable
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Check if secret has a value
        if: ${{ env.job_secret != '' }}
        run: echo 'The secret has a value set.'

      - name: Check if secret is empty
        if: ${{ env.job_secret == '' }}
        run: echo 'The secret does not have a value set.'

      - name: Display secret value
        run: echo ${{ env.job_secret }}
