name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: Greeting One
      run: echo "Hello how are you?"
    - name: Greeting Step 
      run: |
        echo "I am awesome !"
        echo "how are you?"
        


      
  
