name: Example Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test Database Connectivity
        with:
          db_username: ${{ secrets.DBUserName }}
          db_password: ${{ secrets.DBPassword }}
        run: echo $db_username $db_password




          