name: Example Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test Database Connectivity
        run: echo ${{ secrets.DBUserName }} ${{ secrets.DBPassword }}

      - shell: pwsh
        env:
          DB_PASSWORD: ${{ secrets.DBPassword }}
        run: |
          echo "$env:DB_PASSWORD"  
