name: context workflow
on: push
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: check github context
        run: echo "${{ toJSON(github) }}"
      - name: welcome
        run: echo "Welcome"
        
